OS_1: linux
OS_2: linux
TANZU_CLI_URL: http://ralph.simpson:33000/mtritab/cli/raw/branch/master/tanzu-cli-1.5-bundle-linux-amd64.tar
TANZU_CLI_VER: v0.11.6
KUBECTL_CLI_URL: http://ralph.simpson:33000/mtritab/cli/raw/branch/master/kubectl-linux-v1.22.9+vmware.1.gz
YQ_CLI_URL: https://github.com/mikefarah/yq/releases/download/v4.18.1/yq_linux_amd64
