---
- name: Cli-Setup
  hosts: localhost
  tasks:
  - name: tanzu-cli-install
    include_role:
      name: tanzu-cli-install
      apply:
        tags:
        - tanzu-cli-install
    tags:
    - tanzu-cli-install

  - name: kubectl-install
    include_role:
      name: kubectl-install
      apply:
        tags:
        - kubectl-install
    tags:
    - kubectl-install

  - name: carvel-install
    include_role:
      name: carvel-install
      apply:
        tags:
        - carvel-install
    tags:
    - carvel-install

  - name: yq-install
    include_role:
      name: yq-install
      apply:
        tags:
        - yq-install
    tags:
    - yq-install

