---
- name: cluster-teardown
  hosts: localhost
  vars_files:
  -  "~/.config/tanzu/clusters/{{ CLUSTER_NAME }}/cluster-config.yaml"
  -  "~/.config/tanzu/clusters/{{ CLUSTER_NAME }}/ansible-config.yaml"

  tasks:
  - name: tmc-cluster-unmanage
    include_role:
      name: tmc-cluster-unmanage
      apply:
        tags:
        - tmc-cluster-unmanage
    tags:
    - tmc-cluster-unmanage

  - name: cluster-delete
    include_role:
     name: cluster-delete
     apply:
       tags:
       - cluster-delete
    tags:
    - cluster-delete

