---
- name: management-cluster-create
  command: "tanzu management-cluster create {{ CLUSTER_NAME }} -f ~/.config/tanzu/clusters/{{ CLUSTER_NAME }}/cluster-config.yaml"
  register: out
- debug: var=out.stdout_lines
