---
- name: tanzu-management-cluster-delete
  shell: |
    export PATH={{ ansible_env.PATH }}:{{ BIN_DIR }}
    tanzu management-cluster delete {{ CLUSTER_NAME }} -y
  args:
    executable: /bin/bash
  register: out
- debug: var=out.stdout_lines
