---
# get OS specific vars, urls to download binaries, and location to install
- name: get-os-vars
  include_vars: "group_vars/{{ ansible_facts.system|lower }}.yaml"

- name: Create a directory if it does not exist
  file:
    path: "{{ BIN_DIR }}"
    state: directory
    mode: '0755'

# download yq binary
- name: download-yq
  get_url:
    url: "{{ YQ_CLI_URL }}"
    dest: "{{ BIN_DIR }}/yq"
    mode: '0755'
