---
- name: tanzu-export-management-kubeconfig
  shell: |
    export PATH={{ ansible_env.PATH }}:{{ BIN_DIR }}
    tanzu management-cluster kubeconfig get --export-file ~/.config/tanzu/clusters/{{ CLUSTER_NAME }}/config --admin
  register: out
